// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwVhh0RiWjwRgwek0TE7b7-73Ru4u7iGo',
    appId: '1:507116110863:android:349e04eda633f805c4cf7a',
    messagingSenderId: '507116110863',
    projectId: 'ecommercefull122',
    storageBucket: 'ecommercefull122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtPuEpfpKqdwAEZFCcf1IJgBNu2JdfvDo',
    appId: '1:507116110863:ios:9a60f729d794b26bc4cf7a',
    messagingSenderId: '507116110863',
    projectId: 'ecommercefull122',
    storageBucket: 'ecommercefull122.firebasestorage.app',
    androidClientId: '507116110863-ica4m60bmcf5tmh5ulocd173bmsiir6d.apps.googleusercontent.com',
    iosClientId: '507116110863-oggnsha7io64mbae8ffi1m5eu1oj8sc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceDeliveryApp',
  );
}
